name = "fortran-forum-article-template"
version = "21.02.25"
license = "BSD"
author = ["Bradley Richardson and Damian Rouson"]
maintainer = "brad@sourceryinstitute.org"
copyright = "2021 Sourcery Institute"

[dependencies]
sourcery = {git = "https://github.com/sourceryinstitute/sourcery", tag = "21.02.24"}

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.0.2"}

[[test]]
name="unit"
source-dir="tests"
main="main.f90"
